### PR TITLE
Bypass CE cacher when retrieving artifacts

### PR DESCRIPTION
**Pull request by osnipso**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket
- [X] Attached commits represent units of work and are properly formatted
- [X] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [X] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by ryanemerson** [comment]
@osnipso You also need to update the zip name in `image.yaml` and `modules/datagrid/distribution/install.sh
` to `jboss-datagrid-7.3.0-1-server.zip`

**Comment by osnipso** [comment]
@ryanemerson good catch, updated. :+1:

**Comment by osnipso** [comment]
@ryanemerson good catch :+1:
Updated, will look if there's any other place that needs to be changed, just to be on the safe side.

**Comment by ryanemerson** [comment]
Merged ... The CI is able to build the image and the changes should effect the behaviour of the actual tests.

**Pull request merged**
