### PR TITLE
cloud-1980 add/update JAVA_OPTS_APPEND and JBOSS_MODULES_SYSTEM_PKGS_…

### PR DESCRIPTION
**Pull request by bdecoste**
…APPEND

### CODE REVIEW

**Comment by galderz** [comment]
Is this still relevant? @osnipso @ryanemerson?

**Comment by galderz** [comment]
Is this still relevant? @osnipso @ryanemerson?

**Comment by galderz** [comment]
Is this still relevant? @osnipso @ryanemerson?

**Comment by ryanemerson** [comment]
@galderz It is just adding descriptions to the `image.yaml` which AFAIK doesn't really add anything as these are already in our docs. Closing as it's on the 7.1 branch.

**Pull request closed without merging**
