### PR TITLE
[JDG-5257] Add group to openshift API.

### PR DESCRIPTION
**Pull request by rigazilla**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [X] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket
- [X] Attached commits represent units of work and are properly formatted
- [X] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [X] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

Ungrouped API are deprecated on OCP since 4.7
https://issues.redhat.com/browse/JDG-5257

### CODE REVIEW

**Comment by yselkowitz** [comment]
There is one template which still uses `apps/v1beta1` instead of `apps/v1` for `StatefulSet`, but otherwise LGTM.

**Comment by rigazilla** [comment]
> There is one template which still uses `apps/v1beta1` instead of `apps/v1` for `StatefulSet`, but otherwise LGTM.

fixed, thanks!

**Comment by ryanemerson** [comment]
Thanks @rigazilla

**Comment by yselkowitz** [comment]
This needs to also land in the datagrid73 branch.

**Pull request merged**
