### PR TITLE
Update artifact to 7.3.2.ER1

### PR DESCRIPTION
**Pull request by osnipso**
Using full server distribution; let's decide if this should be the approach moving forward.
Cons: the patch is not available for download directly through Brew, so an override file for downloading from `http://download.eng.bos.redhat.com/devel/candidates/JDG/` when building internally and instructions on how to provide the artifact for a local build would be necessary (or, some other way of doing it, open for discussion).

Signed-off-by: Osni Oliveira <osni.oliveira@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [X] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket
- [X] Attached commits represent units of work and are properly formatted
- [X] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [X] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by ryanemerson** [comment]
@osnipso Green :smile:. I updated the CI to have the required docker packages, so the CI should be somewhat usable, I'm sure we'll still have the flaky issues with `oc cluster up`.

**Comment by ryanemerson** [comment]
@osnipso Regarding patch vs server, let's go with the latter and keep things simple. I see no value added in going down the patch route.

There is a conflict that needs resolving before I can merge though.

**Comment by osnipso** [comment]
> @osnipso Regarding patch vs server, let's go with the latter and keep things simple. I see no value added in going down the patch route.

@ryanemerson I understand and agree, would prefer to stick with server myself. However, let's not forget this was something that went through a customer requirement and caused some issues in the past (i.e. the customer wanting access to download the artifact for the full server distribution for each version on prem), so I think we should at least mention it to the other guys.

> There is a conflict that needs resolving before I can merge though.

I have manually rebased the branch on top of current HEAD, it should be good to go.

**Comment by ryanemerson** [comment]
> so I think we should at least mention it to the other guys.

Yeah we should definitely make people aware.

**Pull request merged**
