### PR TITLE
JDG-2234 Remove unused container templates from configuration

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/JDG-2234

### CODE REVIEW

**Comment by ryanemerson** [comment]
@galderz Test fails because they utilise the "replicated" template. Tests need to be updated in light of desired semantics of both the caching and datagrid service.

**Comment by galderz** [comment]
@ryanemerson Sure, no problems. The XML you have to pass in can be finicky so try out outside OpenShift first. I'll have to do the same my existing persistent data work and the blueprint tutorial.

**Comment by galderz** [comment]
@ryanemerson Sure, no problems. The XML you have to pass in can be finicky so try out outside OpenShift first. I'll have to do the same my existing persistent data work and the blueprint tutorial.

**Comment by galderz** [comment]
@ryanemerson Sure, no problems. The XML you have to pass in can be finicky so try out outside OpenShift first. I'll have to do the same my existing persistent data work and the blueprint tutorial.

**Review by galderz — DISMISSED** [review]
Fix the CI and this is good to go.

**Comment by ryanemerson** [comment]
@galderz Should be good to go now

**Review by galderz — APPROVED** [review]
Nice and quick, thanks!

**Pull request merged**
