### PR TITLE
CLOUD-2389 JDG 7.2 templates

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/CLOUD-2389

### CODE REVIEW

**Comment by goldmann** [comment]
Would it make sense to put the image stream definition into the `templates/` directory? I'm just thinking about general guidelines since we will need to do it for every product at some point.

**Comment by slaskawi** [comment]
@goldmann It depends. I noticed that the CE Team prefer keeping them together whereas the OpenShift Online team prefer keeping them separate (see the [library](https://github.com/openshift/library/tree/master/official/datagrid)). Having in mind that you need to add all the references manually (to both library and OpenShift Ansible Installer) - does it matter?

**Comment by goldmann** [comment]
I guess the reason for putting them into templates is that it will be a single file, for any branch. The library example you mentioned hosts multiple files, for different versions, which is not true here.

Either case, I'm easy. I probably don't like the '_' char in the name :)

**Comment by slaskawi** [comment]
Ok, no problem. I put both of them in `templates`. Cheers!

**Review by rcernich — APPROVED** [review]
LGTM

**Pull request merged**
