### PR TITLE
Upgrade to Java 11

### PR DESCRIPTION
**Pull request by ryanemerson**
Eurgh that was painful to get to the bottom of :mask:

### CODE REVIEW

**Comment by ryanemerson** [comment]
This also works when applied on top of https://github.com/jboss-container-images/jboss-datagrid-7-openshift-image/pull/178. Personally I think the simplicity of the former makes it worth merging, but as we're on patch releases I understand the hesitation.

**Comment by osnipso** [comment]
Just waiting for #180 to be merged before this one.

**Review by osnipso — COMMENTED** [review]
@ryanemerson as I ran this (`docker run <image>`) on top of HEAD, a last time before merging, I got:
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jolokia.util.ClassUtil (file:/opt/jboss/container/jolokia/jolokia-jvm-1.5.0.redhat-1-agent.jar) to constructor sun.security.x509.X500Name(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jolokia.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`
Do you know what's happening? I don't remember those warnings the last time I tested it, but I do remember I was getting them on my previous WIP PR for Java 11.

**Comment by ryanemerson** [comment]
The warnings are because Jolokia has not been modified for java 11. Until that happens, we have to live with the warnings unfortunately.

See https://github.com/rhuss/jolokia/issues/394 for more details.

**Review by osnipso — APPROVED** [review]
From CI, I'm getting `ERROR    Required CEKit library 'python-docker' was not found; required module 'docker' could not be found. Try to install the 'python-docker-py' package.`.
Running the tests locally, I've got inconsistent results. Took me several runs to get one working, even with the increased Arquillian timeouts (maybe it's my setup?). Here's a log with a successful run: https://pastebin.com/mk7wjrYt
Other changes look good to me, I'm merging.

**Pull request merged**
