### PR TITLE
JDG-2527 Add missing XML elements

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/JDG-2527

### CODE REVIEW

**Comment by galderz** [comment]
Let's see CI

**Comment by Crumby** [comment]
You missed `MFC` -> `MFC_NB` in jgroups tcp stack

**Comment by galderz** [comment]
@Crumby Fixed and pushed

**Comment by galderz** [comment]
Dunno what's up with CI:
```
error parsing HTTP 400 response body: unexpected end of JSON input: ""
make: *** [push-image-common] Error 1
```

Locally it all works fine.

**Comment by ryanemerson** [comment]
thanks @galderz

**Pull request merged**
