### PR TITLE
update imagestreams to registry.redhat.io

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@goldmann these changes are needed for the new registry.  i've submitted the PR against the branch that openshift/library is currently pulling from, but if you have an upstream dev branch, these changes need to be made there too.

**Comment by osnipso** [comment]
@bparees we do have an upstream dev branch, datagrid72-dev. In fact, I'm just about to merge some changes in our image streams and templates there, because we are doing the release for version 1.1 (which will need to be in the new registry, too, I assume). Since right after releasing I'll sync the -dev branch with this ga/release one, do you mind if I cherry-pick your patch there, so it will end up here after syncing?

**Comment by bparees** [comment]
@osnipso not at all.  whatever makes sense for you guys to get these changes where they need to go.

**Comment by bparees** [comment]
@osnipso did you create another PR somewhere?  i'm trying to track that all these get updated as needed.

**Comment by osnipso** [comment]
@bparees what a coincidence, I just verified if your other PR in `application-templates` has already been merged, so I can process this one, too. No, I'll just keep your PR here, until the moment of integrating this code changes comes (so, it's easy for you to keep an eye, too). Then, I'll open the PR against `datagrid72-dev` branch, reference this one, and close it once I integrate the one that is going in. After releasing from the sprint, all branches will be synced, so your code changes will end up here via sync process. I can give word once this all happens, if you want.

**Comment by bparees** [comment]
>  I can give word once this all happens, if you want.

that'd be great, thanks!

**Comment by osnipso** [comment]
Superseded by #91 (upstream -dev branch). After releasing images from CE Sprint 23, it will be synced here.

**Pull request closed without merging**
